"""Initial schema with shops, projects, imports, and sync

Revision ID: 7651c38f05e2
Revises: 
Create Date: 2026-03-11 23:33:02.106534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7651c38f05e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mergado_shop_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('shopify_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_mergado_shop_id'), ['mergado_shop_id'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('mergado_project_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('output_url', sa.String(length=500), nullable=True),
    sa.Column('output_format', sa.String(length=50), nullable=True),
    sa.Column('shopify_id_element_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_mergado_project_id'), ['mergado_project_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_shop_id'), ['shop_id'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)

    op.create_table('sync_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sync_type', name='uq_project_sync_type')
    )
    with op.batch_alter_table('sync_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_configs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_configs_sync_type'), ['sync_type'], unique=False)

    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('product_identifier', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=50), nullable=True),
    sa.Column('shopify_variant_id', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_logs_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_logs_product_identifier'), ['product_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_logs_shopify_product_id'), ['shopify_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_logs_status'), ['status'], unique=False)

    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_config_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_synced', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['sync_config_id'], ['sync_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_logs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_sync_config_id'), ['sync_config_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_logs_sync_config_id'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_status'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_started_at'))

    op.drop_table('sync_logs')
    with op.batch_alter_table('import_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_logs_status'))
        batch_op.drop_index(batch_op.f('ix_import_logs_shopify_product_id'))
        batch_op.drop_index(batch_op.f('ix_import_logs_product_identifier'))
        batch_op.drop_index(batch_op.f('ix_import_logs_import_job_id'))
        batch_op.drop_index(batch_op.f('ix_import_logs_created_at'))

    op.drop_table('import_logs')
    with op.batch_alter_table('sync_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_configs_sync_type'))
        batch_op.drop_index(batch_op.f('ix_sync_configs_project_id'))

    op.drop_table('sync_configs')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_created_at'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_shop_id'))
        batch_op.drop_index(batch_op.f('ix_projects_mergado_project_id'))

    op.drop_table('projects')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_mergado_shop_id'))

    op.drop_table('shops')
    # ### end Alembic commands ###
